### ISSUE TITLE
Bug; Pause is borked

### ISSUE THREAD

**Issue by Horizon35m** [Horizons-Adventure/Horizons-Adventure-Client#5]
When you pause your game advancements is overtop options.
![image](https://user-images.githubusercontent.com/92321696/175813350-f04f6490-abab-4b40-ad16-51e59f22b566.png)

**Comment by DomiiBunn** [comment]
Fixed in [140413a](https://github.com/Horizons-Adventure/Horizons-Adventure-Client/commit/140413a97d46c2715912833e87a8aea15db2a7bd)
